package pgdata;

import Constant.Constant;
import Controller.RandomData;
import DataStructure.DynamicByteBuffer;
import ParseData.DataConvert;

/**
 * All the device logs are generated by Device itself
 * The logs have nothing to do with programmer itself
 */
public class DeviceFaultLog extends BaseFakeDataGenerator{
    private byte[] packetHeader = {(byte) 0x80, 0x63, 0x14};
    private byte[] payload;
    private byte[] CRC32;
    private DynamicByteBuffer buffer;
    public DeviceFaultLog(){
        buffer = new DynamicByteBuffer();
        payload = null;
        for(int i = 0;i<15;i++){
            FaultLog log = new FaultLog();
            buffer.put(log.getFaultLog());
        }

    }


    private class FaultLog{
        private byte[] timestamp;
        private byte[] faultCount;
        private byte faultId;
        private byte reserved = 0x00;
        public FaultLog(){
            randomize();
        }

        public void randomize(){
            timestamp = RandomData.generateRandomBytes(4);
            faultCount = RandomData.generateRandomBytes(2);
            faultId = RandomData.generateRandomByte();
        }

        public byte[] getFaultLog(){
            DynamicByteBuffer buffer = new DynamicByteBuffer();
            buffer.put(timestamp);
            buffer.put(faultCount);
            buffer.put(faultId);
            buffer.put(reserved);
            return buffer.toArray();
        }
    }

    @Override
    public byte[] getbRetrunData() {
        DynamicByteBuffer dataBuffer = new DynamicByteBuffer();
        dataBuffer.put(0,buffer.toArray());
        // 将ByteBuffer转化为byte数组
        payload = dataBuffer.toArray();

        byte[] parameterCRC32 = DataConvert.calculateCRC32(payload, 0, payload.length);
        dataBuffer.put(parameterCRC32);

        byte[] packetBody = dataBuffer.toArray();
        byte[] CRC32 = DataConvert.calculateCRC32(packetBody, 0, packetBody.length);

        dataBuffer.put(CRC32);
        dataBuffer.put(0, packetHeader);

        bRetrunData = dataBuffer.toArray();

        return bRetrunData;
    }

}
