package pgdata.DeviceLog;

import Controller.RandomData;
import DataStructure.DynamicByteBuffer;
import ParseData.DataConvert;

/**
 * All the device logs are generated by Device itself
 * The logs have nothing to do with programmer itself
 */
public class DeviceFaultLog extends BaseLog {
    private int deviceMode;
    private int testCaseId;
    public DeviceFaultLog(){
        packetHeader = new byte[]{(byte) 0x83, 0x63, 0x14};
    }
    public DeviceFaultLog(int deviceMode, int testCaseId){
        this();
        this.deviceMode = deviceMode;
        this.testCaseId = testCaseId;
    }

    private class FaultLog{
        private byte[] timestamp;
        private byte[] faultCount;
        private byte faultId;
        private byte status;
        public FaultLog(int deviceMode, int testCaseId){
            timestamp = RandomData.getTimePassedInSeconds(0,0,0);
            faultId = (byte)(deviceMode);
            faultCount = RandomData.generateByteArray(2,deviceMode*111);
            status = (byte)(testCaseId*3);
        }

        public byte[] getFaultLog(){
            DynamicByteBuffer buffer = new DynamicByteBuffer();
            buffer.put(timestamp);
            buffer.put(faultCount);
            buffer.put(faultId);
            buffer.put(status);
            return buffer.toArray();
        }
    }

    public void buildPayload(DynamicByteBuffer buffer){
        for(int i = 0;i<15;i++){
            FaultLog log = new FaultLog(deviceMode, testCaseId);
            buffer.put(log.getFaultLog());
        }
    }
}
