package ParseData;

/**
 * ICD Command Definitions
 */
public interface ICDCommandDefinitions {
    // ICD Command Definitions
    public static final int
            HOST_CMD_NO_OPERATION = 0x00,
            ICD_CMD_EXIT_STORAGE = 0x01, //06
            ICD_CMD_READ_ALERT_PARAM = 0x02, //0C
            ICD_CMD_DIVERT = 0x03, //12
            ICD_CMD_READ_TACHY_DETECT_PARAM = 0x04, //1B
            ICD_CMD_MANUAL_ATP_EXEC = 0x05, //21
            ICD_CMD_ABORT_COMMANDED_SHOCK = 0x06, //23
            ICD_CMD_ABORT_SHOCK_ON_T = 0x07, //29
            ICD_CMD_BACK_TO_STORAGE_MODE = 0x08, //47
            ICD_CMD_START_PES = 0x09, //4D
            ICD_CMD_START_STAT_SHOCK = 0x0A, //50
            ICD_CMD_READ_EPISODE_HEADER = 0x0B, //51
            ICD_CMD_READ_PATIENT_LEADS_INFO = 0x0C, //59
            ICD_CMD_READ_SERIAL_MODEL_NUM = 0x0D, //63
            ICD_CMD_READ_DAILY_MMT_HEADER = 0x0E, //69
            ICD_CMD_READ_CLINICIAN_NOTE = 0x0F, //6C
            ICD_CMD_READ_TACHY_LOG = 0x10, //6D
            ICD_CMD_READ_DEVICE_RESET_LOG = 0x11, //6E
            ICD_CMD_TRIGGER_WDT = 0x12, //6F
            ICD_CMD_CLEAR_RESET_LOG = 0x13, //70
            ICD_CMD_READ_DEVICE_FAULT_LOG = 0x14, //71
            ICD_CMD_READ_TACHY_MODE = 0x15,
            ICD_CMD_READ_HV_CAP_VOLTAGE = 0x16,
            ICD_CMD_RETRIEVE_M2_TIMER = 0x17, //74
            ICD_CMD_MANUAL_CAPACITOR_REFORM = 0x18, //75
            ICD_CMD_RETRIEVE_PG_TIMER_AND_RTC_DELTA = 0x19, //77
            ICD_CMD_CLEAR_TACHY_LOG = 0x1A, //78
            ICD_CMD_RETRIEVE_RATE_HISTOGRAM = 0x1B, //79
            ICD_CMD_RETRIEVE_RATE_HISTOGRAM_LIFETIME = 0x1C, //7A
            ICD_CMD_CLEAR_RATE_HISTOGRAM = 0x1D, //7B
            ICD_CMD_CLEAR_RATE_HISTOGRAM_LIFETIME = 0x1E, //7C
            ICD_CMD_CONTINUE_MANUAL_BURST_PACING = 0x1F, //7F
            ICD_CMD_READ_CAPACITOR_REFORM = 0x20, //81
            ICD_CMD_CLEAR_DAILY = 0x21, //83
            ICD_CMD_MANUAL_INTRINSIC_MEASUREMENT = 0x22, //84
            ICD_CMD_CLEAR_ALL_LOG = 0x23, //85
            ICD_CMD_READ_GLOBAL_CONSTANTS = 0x24, //88
            ICD_CMD_CLEAR_CHARGE_LOG = 0x25, //89
            ICD_CMD_READ_TACHY_SVT_PARAM = 0x26, //8C
            ICD_CMD_FIRMWARE_VERSION = 0x27, //B5
            ICD_CMD_READ_FOLLOW_UP_DATE = 0x28, //BB
            ICD_CMD_READ_PACE_THRESHOLD_LOG = 0x29, //split from test cmd
            ICD_CMD_READ_LAST_MEASUREMENTS = 0x2A,
            ICD_CMD_READ_GLOBAL_COUNTERS = 0x2B,
            ICD_CMD_CLEAR_LAST_SESSION_COUNTERS = 0x2C,
            ICD_CMD_CLEAR_FAULT_LOG = 0x2D,
            ICD_CMD_READ_ALARM_LOG = 0x2E,
            ICD_CMD_READ_BRADY_COUNTERS = 0x2F,
            ICD_CMD_READ_BATTERY_LOG = 0x30,
    //NULL, //0x31
    //NULL, //0x32
    //NULL, //0x33
    //NULL, //0x34
    //NULL, //0x35
    //NULL, //0x36
    //NULL, //0x37
    ICD_CMD_WRITE_ENTRY_DEVICELOG = 0x38, //72
            ICD_CMD_WRITE_DEVICE_LOG_FRAM = 0x39, //73
            ICD_CMD_ENTER_SAFE_MODE = 0x3A, //01
            ICD_CMD_EXIT_SAFE_MODE = 0x3B, //02
            ICD_CMD_ACTIVE_PACING = 0x3C, //08
            ICD_CMD_EMERGENCY_STOP = 0x3D, //09
            ICD_CMD_SET_POST_SHOCK_PACING_PARAM = 0x3E, //0D
            ICD_CMD_READ_POST_SHOCK_PACING_PARAM = 0x3F, //0E
            ICD_CMD_START_INDUCE_FIBRILLATE = 0x40, //13
            ICD_CMD_STOP_INDUCE_FIBRILLATE = 0x41, //14
            ICD_CMD_READ_ICD_DATE_TIME = 0x42, //18
            ICD_CMD_SET_ICD_DATE_TIME = 0x43, //19
            ICD_CMD_SET_ATP_PARAM = 0x44, //1E
            ICD_CMD_READ_ATP_PARAM = 0x45, //1F
            ICD_CMD_SYNC_SHOCK = 0x46, //03
            ICD_CMD_ASYNC_SHOCK = 0x47, //04
            ICD_CMD_SET_BRADY_PARAM = 0x48, //05
            ICD_CMD_START_MANUAL_BURST_PACING = 0x49, //07
            ICD_CMD_READ_BRADY_PARAM = 0x4A, //0A
            ICD_CMD_SET_ALERT_PARAM = 0x4B, //0B
            ICD_CMD_DISCHARGE_CAPACITOR = 0x4C, //0F
            ICD_CMD_CHARGE_CAPACITOR = 0x4D, //10
            ICD_CMD_DUMP_CAPACITOR = 0x4E, //11
            ICD_CMD_MEASURE_PACE_IMPEDANCE = 0x4F, //15
            ICD_CMD_MEASURE_SHOCK_IMPEDANCE = 0x50, //16
            ICD_CMD_MEASURE_BATTERY_VOLTAGE = 0x51, //17
            ICD_CMD_SET_TACHY_DETECT_PARAM = 0x52, //1A
            ICD_CMD_SET_TACHY_THERAPY_PARAM = 0x53, //1C
            ICD_CMD_READ_TACHY_THERAPY_PARAM = 0x54, //1D
            ICD_CMD_SET_MANUAL_ATP_PARAM = 0x55, //20
            ICD_CMD_START_COMMANDED_SHOCK = 0x56, //22
            ICD_CMD_START_SHOCK_ON_T = 0x57, //28
            ICD_CMD_READ_DAILY_MMT = 0x58, //30
            ICD_CMD_MEASURE_BODY_TEMPERATURE = 0x59, //31
            ICD_CMD_START_STAT_PACE = 0x5A, //32
            ICD_CMD_START_TEMP_BRADY = 0x5B, //33
            ICD_CMD_EXIT_TEMP_BRADY = 0x5C, //34
            ICD_CMD_START_ELECTROCAUTERY_MODE = 0x5D, //37
            ICD_CMD_STOP_ELECTROCAUTERY_MODE = 0x5E, //38
            ICD_CMD_SET_SENSITIVITY_PARAM = 0x5F, //39
            ICD_CMD_READ_SENSITIVITY_PARAM = 0x60, //3A
            ICD_CMD_START_MRI_MODE = 0x61, //4A
            ICD_CMD_STOP_MRI_MODE = 0x62, //4B
            ICD_CMD_SET_PES_PARAM = 0x63, //4C
            ICD_CMD_READ_SINGLE_EPISODE = 0x64, //52
            ICD_CMD_READ_SINGLE_SEGMENT = 0x65, //53
            ICD_CMD_DELETE_EPISODE = 0x66, //54
            ICD_CMD_READ_SEGMENT_MARKERS = 0x67, //55
            ICD_CMD_SET_PATIENT_INFO = 0x68, //56
            ICD_CMD_READ_PATIENT_INFO = 0x69, //57
            ICD_CMD_SET_PATIENT_LEADS_INFO = 0x6A,//58
            ICD_CMD_SET_SERIAL_MODEL_NUM = 0x6B, //62
            ICD_CMD_SET_CLINICIAN_NOTE = 0x6C, //6B
            ICD_CMD_PROGRAM_RTC_DELTA = 0x6D, //76
            ICD_CMD_SET_MAGNET_MODE = 0x6E, //7D
            ICD_CMD_CONFIGURE_FARFIELD = 0x6F, //7E
            ICD_CMD_SET_FOLLOW_UP_DATE = 0x70, //BA
            ICD_CMD_UNIVERSAL_ABORT = 0x71, //82
            ICD_CMD_MANUAL_PACE_THRESHOLD_TEST = 0x72, //86
            ICD_CMD_SET_GLOBAL_CONSTANTS = 0x73, //87
            ICD_CMD_READ_CHARGE_LOG = 0x74, //8A
            ICD_CMD_SET_TACHY_MODE = 0x75, //8B
            ICD_CMD_SET_TACHY_SVT_PARAM = 0x76, //8D
            ICD_CMD_MANUAL_MORPHOLOGY_CAPTURE = 0x77, //8E
            ICD_CMD_BL_UPGRADE_DESCRIPTOR = 0x78, //AA OTA
            ICD_CMD_BL_UPGRADE_PROGRAM = 0x79, //AB
            ICD_CMD_BL_UPGRADE_VERIFY = 0x7A, //AC
            ICD_CMD_BL_UPGRADE_CONFIRM = 0x7B, //AD
            ICD_CMD_BL_UPGRADE_RESET = 0x7C, //AE
    //NULL, //0x78
    //NULL, //0x79
    //NULL, //0x7A
    //NULL, //0x7B
    //NULL, //0x7C
    //NULL, //0x7D
    ICD_CMD_READ_FROM_FRAM = 0x7E, //B3
            ICD_CMD_WRITE_TO_FRAM = 0x7F, //B4
            ICD_CMD_BLE_IN_SESSION = 0x80, //80 keep alive
            ICD_CMD_PROGRAM_CALIBRATION_CONSTANT = 0x81, //BC
            ICD_CMD_READ_CALIBRATION_CONSTANT = 0x82, //BD
            ICD_CMD_FORCE_MCU_RESET = 0x83,
    //NULL, //0x84
    //NULL, //0x85
    //NULL, //0x86
    ICD_CMD_SAFETY_CORE_PARAM = 0x87,
            ICD_CMD_READ_BATTERY_DETAIL = 0x88,
            ICD_CMD_SET_BATTERY_ESTIMATE_CONSTANTS = 0x89,
    //NULL, //0x8A
    //NULL, //0x8B
    ICD_CMD_SET_MANUAL_BURST_PARAM = 0x8C, //24
            ICD_CMD_READ_MANUAL_BURST_PARAM = 0x8D, //25
            ICD_CMD_SET_VF_INDUCTION_PARAM = 0x8E, //26
            ICD_CMD_READ_VF_INDUCTION_PARAM = 0x8F, //27
            ICD_CMD_SET_MAGN_BUZ_SETTING_PARAM = 0x90, //2A
            ICD_CMD_READ_MAGN_BUZ_SETTING_PARAM = 0x91, //2B
            ICD_CMD_SET_AUTO_THRAPY_PARAM = 0x92, //2C
            ICD_CMD_SET_EP_TEST_PARAM = 0x93, //2D
            ICD_CMD_READ_EP_TEST_PARAM = 0x94, //2E
            ICD_CMD_SET_DAILY_MMT_PARAM = 0x95, //2F
            ICD_CMD_ENABLE_BLUETOOTH = 0x96, //35
            ICD_CMD_GET_BLUETOOTH_CONFIG = 0x97, //36
            ICD_CMD_DUMP_FOR_IMPEDANCE = 0x98, //2F
            ICD_CMD_M1_UPDATE_FIRMWARE_INFO = 0x99, //3C
            ICD_CMD_M2_UPDATE_FIRMWARE_INFO = 0x9A, //3D
            ICD_CMD_M3_UPDATE_FIRMWARE_INFO = 0x9B, //3E
            ICD_CMD_M1_UPDATE_FIRMWARE_DATA = 0x9C, //3F
            ICD_CMD_M2_UPDATE_FIRMWARE_DATA = 0x9D, //40
            ICD_CMD_M3_UPDATE_FIRMWARE_DATA = 0x9E, //41
            ICD_CMD_M1_UPDATE_FIRMWARE_ABORT = 0x9F, //42
            ICD_CMD_M2_UPDATE_FIRMWARE_ABORT = 0xA0, //43
            ICD_CMD_M3_UPDATE_FIRMWARE_ABORT = 0xA1, //44
            ICD_CMD_ACTIVE_ECG_REPORT = 0xA2, //45
            ICD_CMD_BLE_READ_EPISODE = 0xA3, //46
            ICD_CMD_ECG_DATA = 0xA4, //48
            ICD_CMD_ECG_MARKER = 0xA5, //49
            ICD_CMD_CHARGE_DURATION = 0xA6, //4E
            ICD_CMD_DEVICE_STATUS_UPDATE = 0xA7, //4F
            ICD_CMD_SET_PATIENT_INDICATION_INFO = 0xA8, //5A
            ICD_CMD_READ_PATIENT_INDICATION_INFO = 0xA9, //5B
            ICD_CMD_FW_UPGRADE_DESCRIPTOR = 0xAA, //AA OTA
            ICD_CMD_FW_UPGRADE_PROGRAM = 0xAB, //AB
            ICD_CMD_FW_UPGRADE_VERIFY = 0xAC, //AC
            ICD_CMD_FW_UPGRADE_CONFIRM = 0xAD, //AD
            ICD_CMD_FW_UPGRADE_RESET = 0xAE, //
            ICD_CMD_FW_UPGRADE_STATUS = 0xAF, //AF
            ICD_CMD_CHARGE_DONE = 0xB0, //64
            ICD_CMD_DISCHARGE_DUMP_DONE = 0xB1, //65
            ICD_CMD_BLE_READ_TX_POWER = 0xB2,
            ICD_CMD_BLE_WRITE_TX_POWER = 0xB3,
            ICD_CMD_READ_ALERT_CODE = 0xB4, //68
            ICD_CMD_READ_TREAT_SUMMARY_INFO = 0xB5, //6A
            ICD_CMD_READ_TREAT_DETAIL_INFO = 0xB6, //B0
            ICD_CMD_READ_EVENT_EGM_DATA = 0xB7, //B1
            ICD_CMD_READ_THERAPY_EGM_DATA = 0xB8, //B2
            ICD_CMD_M1_VERSION = 0xB9, //B6
            ICD_CMD_M2_VERSION = 0xBA, //B7
            ICD_CMD_M3_VERSION = 0xBB, //B8
            ICD_CMD_MB_VERSION = 0xBC, //B9
            ICD_CMD_RESERVED_0 = 0xBD, //BE
            ICD_CMD_FORCE_RESET_BOOTLOADER = 0xBE, //BF
            ICD_CMD_ACKNOWLEDGE = 0xBF; //CA
}
